# Generated by Django 4.2.6 on 2023-10-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kikitu', '0002_destination_price_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('destination', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=500)),
            ],
        ),
    ]
