# Generated by Django 4.2.6 on 2023-10-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kikitu', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
