# Generated by Django 4.2.6 on 2023-10-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kikitu', '0006_faq_delete_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='itinerary',
            field=models.TextField(default='Default Itinerary'),
        ),
    ]
