# Generated by Django 4.2.6 on 2023-11-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kikitu', '0007_destination_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('price_before', models.FloatField(default=0.0)),
                ('itinerary', models.TextField(default='Default Itinerary')),
            ],
        ),
    ]
